#pragma once

#include "dpt1.h"
#include "dpt2.h"
#include "dpt3.h"
#include "dpt4.h"
#include "dpt5.h"
#include "dpt6.h"
#include "dpt7.h"
#include "dpt8.h"
#include "dpt9.h"
#include "dpt10.h"
#include "dpt11.h"
#include "dpt12.h"
#include "dpt13.h"
#include "dpt14.h"