#ifndef KNX_SERVICE_FAMILY_CORE
#define KNX_SERVICE_FAMILY_CORE 1
#endif

#ifndef KNX_SERVICE_FAMILY_DEVICE_MANAGEMENT
#define KNX_SERVICE_FAMILY_DEVICE_MANAGEMENT 1
#endif

#ifndef KNX_SERVICE_FAMILY_TUNNELING
#define KNX_SERVICE_FAMILY_TUNNELING 1
#endif

#ifndef KNX_SERVICE_FAMILY_ROUTING
#define KNX_SERVICE_FAMILY_ROUTING 1
#endif